### ISSUE TITLE
BC VC Pilot -- what are the rules/options around reuse of an emailed token

### ISSUE THREAD

**Issue by swcurran** [bcgov/trust-over-ip-configurations#90]
We found it odd that an emailed token can be reused -- e.g. clicked on after issuance.  Should that be supported?

I think the behaviour that would be nice to see:

- Once issued, an attempt to reuse the token goes to a page with configurable text.
- An admin can edit the record for the invitation and "uncheck" the "issued" flag -- in which case the user could reuse the token. For this to work, there would likely need to be a "resend email" option.

This is raised for discussion initially to see what behaviour is currently supported so we can decide what we want to do.  Please let us know what is currently supported.

@cvarjao @wadeking98 @esune

**Comment by esune** [comment]
For reference, some of the settings that `issuer-kit` supports are listed [here](https://github.com/bcgov/issuer-kit/blob/main/docs/ConfiguringIssuerKit.md#main-configuration-file). Mostly the restrictions that are applicable are about reusing the same invite more than once and defining a validity after which an unused invite will not be considered valid anymore.

Please note that these settings should work, but have not been as extensively tested as other features since they were more uncommonly required.

**Comment by wadeking98** [comment]
@swcurran The token reuse error was due to an improper check in the navigation guard. I've fixed the issuer in my latest PR to issuer kit
